---

num_rounds: 10
num_clients: 100
num_classes: 10
batch_size: 20
num_clients_per_round_fit: 10
num_clients_per_round_eval: 25
server_momentum: 0.4
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1
